### ISSUE TITLE
Has active development on this project stopped?

### ISSUE THREAD

**Issue by jamesdixon** [waterlock/waterlock#92]
Just curious as I'm a bit hesitant to go into production with it. I'd be more than willing to help out.

**Comment by davidrivera** [comment]
Hey @jamesdixon, i haven't been able to devote as much time as I would like to this project because of work responsibilities and other projects in the pipeline. I have opened waterlock to the community under the [Open-source governance](https://en.wikipedia.org/wiki/Open-source_governance) policy. If you or anyone else would like to have push access to waterlock simply let me know by opening up an issue and I will add you to the organization. I feel you guys can really make this project something I alone could never accomplish and I thank you and everyone else for all of your support :100: 

also I still drop by from time to time to accept pull request and implement some requested features in my spare time (when I have any)

**Comment by wayne-o** [comment]
:+1:

**Comment by jamesdixon** [comment]
Hi @davidrivera, my other engineer (@mlennie) are actively using Waterlock and would be more than happy to contribute to the project and its sub-projects (we're using waterlock-local-auth) as we go along. If you'd like to give me push access, that'd be great. I truly appreciate all the great work you've done thus far. Thanks!

**Comment by robksawyer** [comment]
:+1:

**Comment by wayne-o** [comment]
Closing this issue as active development has indeed not stopped ;)
